version: "3"
services:
  nerfstudio-renderer:
    image: j3soon/nerfstudio-renderer
    build:
      context: .
      args:
        - CUDA_VERSION=11.8.0
        - CUDA_ARCHITECTURES=86
        - OS_VERSION=22.04
        - SERVER_PORT=7007
    container_name: nerfstudio-renderer
    ports:
      - "7007:7007"
    volumes:
      - ./data/outputs:/workspace/outputs
      - cache:/home/user/.cache
    shm_size: '6gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  pygame-window:
    image: j3soon/pygame-window
    build:
      context: tests
    container_name: pygame-window
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./tests:/workspace:ro
    working_dir: /workspace
volumes:
  cache:
